# Generated by Django 3.1 on 2022-01-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20220119_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('isbn', models.CharField(max_length=150)),
                ('book_rating', models.IntegerField()),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=150)),
                ('year_of_publication', models.IntegerField()),
                ('publisher', models.CharField(max_length=150)),
                ('image_url_s', models.CharField(max_length=255)),
                ('image_url_m', models.CharField(max_length=255)),
                ('image_url_l', models.CharField(max_length=255)),
            ],
        ),
    ]
