# Generated by Django 3.1 on 2022-01-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_lower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('book_title',)},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author_name',
            new_name='book_author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='book_title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='book',
            name='type',
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_l',
            field=models.CharField(default='http://images.amazon.com/images/P/0521795028.01.LZZZZZZZ.jpg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_m',
            field=models.CharField(default='http://images.amazon.com/images/P/0521795028.01.MZZZZZZZ.jpg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image_url_s',
            field=models.CharField(default='http://images.amazon.com/images/P/0521795028.01.LZZZZZZZ.jpg', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='empty', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='empty', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year_of_publication',
            field=models.IntegerField(default=1995),
            preserve_default=False,
        ),
    ]
