# Generated by Django 3.1 on 2022-01-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_auto_20220121_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booktype',
        ),
    ]
